version: "3"
services: 
  postgres:
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    # image: 'postgres:latest'
    restart: unless-stopped
    hostname: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackerbook
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    restart: unless-stopped
    depends_on: 
      - postgres
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
  api:
    image: mkozi/gql-api
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    tty: true

volumes:
  db-data:
  pgadmin: